version: "3.9"

services:
  hash1: &hash1
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.native-micro
    hostname: hash1
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "64MB"
  hash2:
    <<: *hash1
    hostname: hash2
    ports:
      - "8082:8080"

  nginx:
    image: nginx:1.28.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hash1
      - hash2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16MB"

networks:
  default:
    driver: bridge
    name: hash-nginx